version: "3.1"

services: 
  adminer: 
    image: adminer
    ports: 
      - "8082:8080"
    restart: always

  db: 
    environment: 
       
        MYSQL_ROOT_PASSWORD: paliroot
       
        MYSQL_DATABASE: transtour
       
        MYSQL_USER: transtourRoot
       
        MYSQL_PASSWORD: transtourRoot
    image: "mysql:5.7"
    ports: 
      - "8081:3306"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
      - $HOME/repositories/transtour/db.sql:/db.sql

volumes: 
  db_data: {}

