version: "3"

services:
  mysqldb:
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: transtour
      MYSQL_USER: transtourRoot
      MYSQL_PASSWORD: transtourRoot
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    container_name: mysqldb
    networks:
      - local
    volumes:
      - "db_data:/var/lib/mysql"
      - $HOME/repositories/transtour/transtour-devops/db.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: transtour
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
    container_name: mongodb
    networks:
      - local
    volumes:
      - $HOME/repositories/transtour/mongo:/data/db

volumes:
  db_data: {}
  vouchers: {}
  travel: {}

networks:
  local:
    driver: bridge